import MySQLdb

conn = MySQLdb.connect(host="localhost", user="deen", passwd="password", db='TWA_YSOS')

cursor = conn.cursor()

cursor.execute ("DROP TABLE IF EXISTS objects")
cursor.execute ("""
    CREATE TABLE objects
    (
       rn   INT(3)
    )
    """)

cursor.execute( "ALTER TABLE objects ADD name VARCHAR(60);")
cursor.execute( "ALTER TABLE objects ADD ra_h INT(3);")
cursor.execute( "ALTER TABLE objects ADD ra_m INT(3);")
cursor.execute( "ALTER TABLE objects ADD ra_s FLOAT(5);")
cursor.execute("ALTER TABLE objects ADD right_ascension DOUBLE PRECISION(12,7);")
cursor.execute( "ALTER TABLE objects ADD dec_h INT(3);")
cursor.execute( "ALTER TABLE objects ADD dec_m INT(3);")
cursor.execute( "ALTER TABLE objects ADD dec_s FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD declination DOUBLE PRECISION(12, 7);")
cursor.execute( "ALTER TABLE objects ADD OPT_SPT FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD IR_SPT FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD EUNC FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD LUNC FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD Aj FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_Aj FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD Aj_SP FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_Aj_SP FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD Aj_SN FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD jband_slope FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_jband_slope FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD rk FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_rk FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD rh FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_rh FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD rj FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_rj FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD lum FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD ew_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_ew_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD ew_pab_flag BOOLEAN;")
cursor.execute( "ALTER TABLE objects ADD ew_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_ew_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD ew_brg_flag BOOLEAN;")
cursor.execute( "ALTER TABLE objects ADD f_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_f_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD f_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_f_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD lacc_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_lacc_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD lacc_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_lacc_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD log_g FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD mass FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD age FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD mdot_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_mdot_pab FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD mdot_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_mdot_brg FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD hyd_R FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD d_hyd_R FLOAT(5);")
cursor.execute( "ALTER TABLE objects ADD binarity INT(3);")
cursor.execute( "ALTER TABLE objects ADD Jmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_Jmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD Hmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_Hmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD Kmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_Kmag FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fIRAC1 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fIRAC1 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fIRAC2 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fIRAC2 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fIRAC3 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fIRAC3 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fIRAC4 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fIRAC4 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fMIPS1 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fMIPS1 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD fMIPS2 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD d_fMIPS2 FLOAT;")
cursor.execute( "ALTER TABLE objects ADD SXD_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD LXD_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD XD_merged VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD IRS_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD SXD_flat VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD LXD_flat VARCHAR(128);")
cursor.execute( "ALTER TABLE objects ADD XD_flat VARCHAR(128);")

cursor.close()
conn.close()

