import MySQLdb

conn = MySQLdb.connect(host="localhost", user="deen", passwd="password", db='sabrmetrics')

cursor = conn.cursor()

cursor.execute ("DROP TABLE IF EXISTS teams")
cursor.execute ("""
    CREATE TABLE teams
    (
       NAME VARCHAR(60)
    )
    """)

cursor.execute( "ALTER TABLE teams ADD TEAMID VARCHAR(60);")
cursor.execute( "ALTER TABLE teams ADD OWNER VARCHAR(60);")
cursor.execute( "ALTER TABLE teams ADD PID1 VARCHAR(10);")
cursor.execute( "ALTER TABLE teams ADD ra_s FLOAT(5);")
cursor.execute("ALTER TABLE teams ADD right_ascension DOUBLE PRECISION(12,7);")
cursor.execute( "ALTER TABLE teams ADD dec_h INT(3);")
cursor.execute( "ALTER TABLE teams ADD dec_m INT(3);")
cursor.execute( "ALTER TABLE teams ADD dec_s FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD declination DOUBLE PRECISION(12, 7);")
cursor.execute( "ALTER TABLE teams ADD OPT_SPT FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD IR_SPT FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD EUNC FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD LUNC FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD Aj FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_Aj FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD Aj_SP FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_Aj_SP FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD Aj_SN FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD jband_slope FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_jband_slope FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD rk FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_rk FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD rh FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_rh FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD rj FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_rj FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD lum FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD ew_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_ew_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD ew_pab_flag BOOLEAN;")
cursor.execute( "ALTER TABLE teams ADD ew_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_ew_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD ew_brg_flag BOOLEAN;")
cursor.execute( "ALTER TABLE teams ADD f_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_f_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD f_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_f_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD lacc_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_lacc_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD lacc_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_lacc_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD log_g FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD mass FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD age FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD mdot_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_mdot_pab FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD mdot_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_mdot_brg FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD hyd_R FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD d_hyd_R FLOAT(5);")
cursor.execute( "ALTER TABLE teams ADD binarity INT(3);")
cursor.execute( "ALTER TABLE teams ADD Jmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_Jmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD Hmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_Hmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD Kmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_Kmag FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fIRAC1 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fIRAC1 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fIRAC2 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fIRAC2 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fIRAC3 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fIRAC3 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fIRAC4 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fIRAC4 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fMIPS1 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fMIPS1 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD fMIPS2 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD d_fMIPS2 FLOAT;")
cursor.execute( "ALTER TABLE teams ADD SXD_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD LXD_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD XD_merged VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD IRS_clean VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD SXD_flat VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD LXD_flat VARCHAR(128);")
cursor.execute( "ALTER TABLE teams ADD XD_flat VARCHAR(128);")

cursor.close()
conn.close()

